name: Build and Deploy # 工作流名称

on:
  push:
    branches:
      - master # 监听 'master' 分支的 push 事件
      - main # 监听 'main' 分支的 push 事件
  workflow_dispatch: # 允许手动触发该工作流

permissions:
  contents: write # 允许写入内容权限
  pages: write # 允许写入 GitHub Pages 权限
  id-token: write # 允许写入 ID Token

jobs:
  build-and-deploy: # 定义任务
    runs-on: ubuntu-latest # 指定运行环境为 Ubuntu 最新版本
    steps:
      - name: Checkout # 获取代码
        uses: actions/checkout@v3 # 使用官方 Checkout Action 获取当前仓库的代码
        with:
          persist-credentials: false # 不持久化凭证，以避免缓存问题

      - name: Setup Node.js # 设置 Node.js 环境
        uses: actions/setup-node@v3 # 使用官方的 Node.js Setup Action
        with:
          node-version: '18' # 使用 Node.js 18 版本（可以根据项目需要调整）

      - name: Install pnpm # 安装 pnpm 包管理器
        run: |
          npm install -g pnpm  # 通过 npm 安装 pnpm
          pnpm --version  # 确认 pnpm 安装成功并输出其版本号

      - name: Install and Build # 安装依赖并构建项目
        run: |
          pnpm install  # 安装项目依赖
          pnpm docs:build  # 构建项目，生成静态文件（此处是构建文档）

      - name: Deploy # 将构建的内容发布到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4 # 使用第三方 Action 来部署到 GitHub Pages
        with:
          BRANCH: gh-pages # 指定部署的分支为 gh-pages
          FOLDER: docs/.vitepress/dist # 构建产物所在文件夹路径
          CLEAN: true # 部署前清理目标文件夹
